### ISSUE TITLE
User update is failing

### ISSUE THREAD

**Issue by NicolasGuary** [drakkan/terraform-provider-sftpgo#2]
Hello @drakkan,
Thank you for making the SFTPGo provider!
Just opening this issue to let you know that the user update is failing with a 404 - Not Found error in case I try to update the username for one user.

Probably because it is looking for the new reference while it should be looking for the old one and update it.

Once again thank you and have a great day!

**Comment by drakkan** [comment]
The same [support policy](https://github.com/drakkan/sftpgo#support-policy) as for SFTPGo applies here
